In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/ellipticco/elliptic-data-set/elliptic_bitcoin_dataset/elliptic_txs_features.csv
/kaggle/input/datasets/ellipticco/elliptic-data-set/elliptic_bitcoin_dataset/elliptic_txs_classes.csv
/kaggle/input/datasets/ellipticco/elliptic-data-set/elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv

In [2]:
!pip install -q ydata-profiling

In [3]:
import pandas as pd
import numpy as np

In [4]:
from ydata_profiling import ProfileReport

/tmp/ipykernel_16/44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [5]:
DATA_PATH = "/kaggle/input/datasets/ellipticco/elliptic-data-set/elliptic_bitcoin_dataset/"

In [6]:
FEATURES_PATH = DATA_PATH + "elliptic_txs_features.csv"
CLASSES_PATH = DATA_PATH + "elliptic_txs_classes.csv"
EDGES_PATH = DATA_PATH + "elliptic_txs_edgelist.csv"

In [7]:
features = pd.read_csv(
    FEATURES_PATH,
    header=None
)

In [8]:
classes = pd.read_csv(CLASSES_PATH)

In [9]:
edges = pd.read_csv(EDGES_PATH)

In [10]:
print("Features:", features.shape)
print("Classes:", classes.shape)
print("Edges:", edges.shape)

Features: (203769, 167)
Classes: (203769, 2)
Edges: (234355, 2)

In [11]:
edges = pd.read_csv(EDGES_PATH)

In [12]:
print("Features:", features.shape)
print("Classes:", classes.shape)
print("Edges:", edges.shape)

Features: (203769, 167)
Classes: (203769, 2)
Edges: (234355, 2)

In [13]:
print("FEATURES")
display(features.head())

print("CLASSES")
display(classes.head())

print("EDGES")
display(edges.head())

FEATURES

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,...,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,...,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,...,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,...,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,...,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117

CLASSES

        txId    class
0  230425980  unknown
1    5530458  unknown
2  232022460  unknown
3  232438397        2
4  230460314  unknown

EDGES

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206

In [14]:
print("Feature columns:", features.columns.tolist()[:10])
print("Class columns:", classes.columns.tolist())
print("Edge columns:", edges.columns.tolist())

Feature columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Class columns: ['txId', 'class']
Edge columns: ['txId1', 'txId2']

In [15]:
feature_names = ["txId", "Time_step"]

for i in range(1, 166):
    feature_names.append(f"feature_{i}")

features.columns = feature_names

In [16]:
print(features.columns.tolist()[:10])
print(features.columns.tolist()[-10:])

['txId', 'Time_step', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8']
['feature_156', 'feature_157', 'feature_158', 'feature_159', 'feature_160', 'feature_161', 'feature_162', 'feature_163', 'feature_164', 'feature_165']

In [17]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203769 entries, 0 to 203768
Columns: 167 entries, txId to feature_165
dtypes: float64(165), int64(2)
memory usage: 259.6 MB

In [18]:
classes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203769 entries, 0 to 203768
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   txId    203769 non-null  int64
 1   class   203769 non-null  object
dtypes: int64(1), object(1)
memory usage: 3.1+ MB

In [19]:
edges.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234355 entries, 0 to 234354
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   txId1   234355 non-null  int64
 1   txId2   234355 non-null  int64
dtypes: int64(2)
memory usage: 3.6 MB

In [20]:
print("===== MISSING VALUES =====")

print("Features:", features.isnull().sum().sum())
print("Classes:", classes.isnull().sum().sum())
print("Edges:", edges.isnull().sum().sum())


print("\n===== DUPLICATES =====")

print("Duplicate feature rows:", features.duplicated().sum())
print("Duplicate txIds:", features["txId"].duplicated().sum())

print("Duplicate class rows:", classes.duplicated().sum())
print("Duplicate class txIds:", classes["txId"].duplicated().sum())

print("Duplicate edges:", edges.duplicated().sum())


print("\n===== CLASS DISTRIBUTION =====")

print(classes["class"].value_counts())
print("\nPercentage:")
print(classes["class"].value_counts(normalize=True) * 100)


print("\n===== TIME STEPS =====")

print("Number of time steps:", features["Time_step"].nunique())
print("Time steps:", sorted(features["Time_step"].unique()))


print("\n===== EDGE VALIDATION =====")

feature_txids = set(features["txId"])

source_missing = (~edges["txId1"].isin(feature_txids)).sum()
target_missing = (~edges["txId2"].isin(feature_txids)).sum()

print("Sources not in features:", source_missing)
print("Targets not in features:", target_missing)


print("\n===== CLASS/FEATURE ID VALIDATION =====")

feature_ids = set(features["txId"])
class_ids = set(classes["txId"])

print("Feature transactions:", len(feature_ids))
print("Class transactions:", len(class_ids))

print("Feature IDs missing from classes:", len(feature_ids - class_ids))
print("Class IDs missing from features:", len(class_ids - feature_ids))


print("\n===== CONSTANT FEATURES =====")

constant_features = []

for col in features.columns:
    if col not in ["txId", "Time_step"]:
        if features[col].nunique() <= 1:
            constant_features.append(col)

print("Number of constant features:", len(constant_features))
print("Constant features:", constant_features)

===== MISSING VALUES =====
Features: 0
Classes: 0
Edges: 0

===== DUPLICATES =====
Duplicate feature rows: 0
Duplicate txIds: 0
Duplicate class rows: 0
Duplicate class txIds: 0
Duplicate edges: 0

===== CLASS DISTRIBUTION =====
class
unknown    157205
2           42019
1            4545
Name: count, dtype: int64

Percentage:
class
unknown    77.148634
2          20.620899
1           2.230467
Name: proportion, dtype: float64

===== TIME STEPS =====
Number of time steps: 49
Time steps: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49)]

===== EDGE VALIDATION =====
Sources not in features: 0
Targets not in features: 0

===== CLASS/FEATURE ID VALIDATION =====
Feature transactions: 203769
Class transactions: 203769
Feature IDs missing from classes: 0
Class IDs missing from features: 0

===== CONSTANT FEATURES =====
Number of constant features: 0
Constant features: []

In [21]:
feature_stats = features.describe().T

display(feature_stats)

,count,mean,std,min,25%,50%,75%,max
txId,203769.0,1.711310e+08,1.104655e+08,1076.000000,8.433452e+07,1.624375e+08,2.454798e+08,4.032446e+08
Time_step,203769.0,2.384396e+01,1.517217e+01,1.000000,9.000000e+00,2.300000e+01,3.800000e+01,4.900000e+01
feature_1,203769.0,2.454849e-17,1.000002e+00,-0.172983,-1.725317e-01,-1.692045e-01,-1.318553e-01,7.168197e+01
feature_2,203769.0,-7.531922e-18,1.000002e+00,-0.210553,-1.803266e-01,-1.328975e-01,-5.524241e-02,7.359505e+01
feature_3,203769.0,2.231681e-17,1.000002e+00,-1.756361,-1.201369e+00,4.636092e-01,1.018602e+00,2.683580e+00
...,...,...,...,...,...,...,...,...
feature_161,203769.0,2.231681e-18,1.000002e+00,-0.125939,-8.749016e-02,-8.749016e-02,-8.749016e-02,2.518490e+02
feature_162,203769.0,5.244450e-17,1.000002e+00,-0.131155,-1.311553e-01,-1.311553e-01,-8.467423e-02,2.387835e+02
feature_163,203769.0,1.562177e-17,1.000002e+00,-0.269818,-1.405971e-01,-9.752359e-02,-9.752359e-02,1.057340e+02
feature_164,203769.0,4.072817e-17,1.000002e+00,-1.760926,-1.206134e-01,-1.206134e-01,1.520067e-01,1.519700e+00
feature_165,203769.0,5.913954e-17,1.000002e+00,-1.760984,-1.197925e-01,-1.197925e-01,1.199710e-01,1.521399e+00

In [22]:
feature_stats[['mean', 'std', 'min', '25%', '50%', '75%', 'max']]

,mean,std,min,25%,50%,75%,max
txId,1.711310e+08,1.104655e+08,1076.000000,8.433452e+07,1.624375e+08,2.454798e+08,4.032446e+08
Time_step,2.384396e+01,1.517217e+01,1.000000,9.000000e+00,2.300000e+01,3.800000e+01,4.900000e+01
feature_1,2.454849e-17,1.000002e+00,-0.172983,-1.725317e-01,-1.692045e-01,-1.318553e-01,7.168197e+01
feature_2,-7.531922e-18,1.000002e+00,-0.210553,-1.803266e-01,-1.328975e-01,-5.524241e-02,7.359505e+01
feature_3,2.231681e-17,1.000002e+00,-1.756361,-1.201369e+00,4.636092e-01,1.018602e+00,2.683580e+00
...,...,...,...,...,...,...,...
feature_161,2.231681e-18,1.000002e+00,-0.125939,-8.749016e-02,-8.749016e-02,-8.749016e-02,2.518490e+02
feature_162,5.244450e-17,1.000002e+00,-0.131155,-1.311553e-01,-1.311553e-01,-8.467423e-02,2.387835e+02
feature_163,1.562177e-17,1.000002e+00,-0.269818,-1.405971e-01,-9.752359e-02,-9.752359e-02,1.057340e+02
feature_164,4.072817e-17,1.000002e+00,-1.760926,-1.206134e-01,-1.206134e-01,1.520067e-01,1.519700e+00
feature_165,5.913954e-17,1.000002e+00,-1.760984,-1.197925e-01,-1.197925e-01,1.199710e-01,1.521399e+00

In [23]:
numeric_features = features.drop(columns=["txId", "Time_step"])

feature_stats = numeric_features.describe().T

display(feature_stats)

,count,mean,std,min,25%,50%,75%,max
feature_1,203769.0,2.454849e-17,1.000002,-0.172983,-0.172532,-0.169204,-0.131855,71.681966
feature_2,203769.0,-7.531922e-18,1.000002,-0.210553,-0.180327,-0.132897,-0.055242,73.595052
feature_3,203769.0,2.231681e-17,1.000002,-1.756361,-1.201369,0.463609,1.018602,2.683580
feature_4,203769.0,6.241732e-17,1.000002,-0.121970,-0.121970,-0.121970,-0.121970,49.027598
feature_5,203769.0,7.653968e-17,1.000002,-0.063725,-0.043875,-0.043875,-0.043875,260.090707
...,...,...,...,...,...,...,...,...
feature_161,203769.0,2.231681e-18,1.000002,-0.125939,-0.087490,-0.087490,-0.087490,251.849028
feature_162,203769.0,5.244450e-17,1.000002,-0.131155,-0.131155,-0.131155,-0.084674,238.783493
feature_163,203769.0,1.562177e-17,1.000002,-0.269818,-0.140597,-0.097524,-0.097524,105.734028
feature_164,203769.0,4.072817e-17,1.000002,-1.760926,-0.120613,-0.120613,0.152007,1.519700
feature_165,203769.0,5.913954e-17,1.000002,-1.760984,-0.119792,-0.119792,0.119971,1.521399

In [24]:
extreme_counts = pd.DataFrame({
    "above_5": (numeric_features.abs() > 5).sum(),
    "above_10": (numeric_features.abs() > 10).sum(),
    "above_50": (numeric_features.abs() > 50).sum(),
    "above_100": (numeric_features.abs() > 100).sum()
})

display(
    extreme_counts[
        (extreme_counts > 0).any(axis=1)
    ].sort_values("above_5", ascending=False)
)

             above_5  above_10  above_50  above_100
feature_38      4093         0         0          0
feature_39      4037         0         0          0
feature_88      2552        44         0          0
feature_22      2322       163         0          0
feature_28      2320       163         0          0
...              ...       ...       ...        ...
feature_155       30         0         0          0
feature_103       27         0         0          0
feature_101       22         0         0          0
feature_89        18         0         0          0
feature_156        9         0         0          0

[107 rows x 4 columns]

In [25]:
print("Unique classes:")
print(classes["class"].unique())

print("\nClass data type:")
print(classes["class"].dtype)

print("\nClass counts:")
print(classes["class"].value_counts())

Unique classes:
['unknown' '2' '1']

Class data type:
object

Class counts:
class
unknown    157205
2           42019
1            4545
Name: count, dtype: int64

In [26]:
print("Number of nodes:", features["txId"].nunique())
print("Number of edges:", len(edges))

print("\nUnique source nodes:", edges["txId1"].nunique())
print("Unique destination nodes:", edges["txId2"].nunique())

print("\nAverage edges per node:", len(edges) / features["txId"].nunique())

Number of nodes: 203769
Number of edges: 234355

Unique source nodes: 166345
Unique destination nodes: 148447

Average edges per node: 1.1501013402431184

In [27]:
in_degree = edges.groupby("txId2").size()
out_degree = edges.groupby("txId1").size()

print("IN-DEGREE")
print(in_degree.describe())

print("\nOUT-DEGREE")
print(out_degree.describe())

print("\nMaximum in-degree:", in_degree.max())
print("Maximum out-degree:", out_degree.max())

IN-DEGREE
count    148447.000000
mean          1.578712
std           4.507890
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         284.000000
dtype: float64

OUT-DEGREE
count    166345.000000
mean          1.408849
std           2.008279
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         472.000000
dtype: float64

Maximum in-degree: 284
Maximum out-degree: 472

In [28]:
all_txids = features["txId"]

in_degree_full = all_txids.map(in_degree).fillna(0)
out_degree_full = all_txids.map(out_degree).fillna(0)

print("Nodes with zero in-degree:", (in_degree_full == 0).sum())
print("Nodes with zero out-degree:", (out_degree_full == 0).sum())

print("\nNodes with both zero:", ((in_degree_full == 0) & (out_degree_full == 0)).sum())

print("\nTotal degree statistics:")
total_degree = in_degree_full + out_degree_full
print(total_degree.describe())

Nodes with zero in-degree: 55322
Nodes with zero out-degree: 37424

Nodes with both zero: 0

Total degree statistics:
count    203769.000000
mean          2.300203
std           4.328377
min           1.000000
25%           1.000000
50%           2.000000
75%           2.000000
max         473.000000
Name: txId, dtype: float64

In [29]:
node_features = features.copy()

node_features["in_degree"] = in_degree_full
node_features["out_degree"] = out_degree_full
node_features["total_degree"] = (
    node_features["in_degree"] +
    node_features["out_degree"]
)

print(node_features.shape)
display(
    node_features[
        ["txId", "Time_step", "in_degree", "out_degree", "total_degree"]
    ].head(10)
)

(203769, 170)

        txId  Time_step  in_degree  out_degree  total_degree
0  230425980          1        1.0         1.0           2.0
1    5530458          1        1.0         1.0           2.0
2  232022460          1        1.0         2.0           3.0
3  232438397          1      160.0         1.0         161.0
4  230460314          1        2.0         8.0          10.0
5  230459870          1        4.0         6.0          10.0
6  230333930          1        0.0         2.0           2.0
7  230595899          1        2.0         1.0           3.0
8  232013274          1        0.0         2.0           2.0
9  232029206          1       59.0         1.0          60.0

In [30]:
node_features["fan_in_out_ratio"] = (
    node_features["in_degree"] /
    node_features["out_degree"].replace(0, 1)
)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "fan_in_out_ratio"
        ]
    ].head(10)
)

(203769, 171)

        txId  in_degree  out_degree  total_degree  fan_in_out_ratio
0  230425980        1.0         1.0           2.0          1.000000
1    5530458        1.0         1.0           2.0          1.000000
2  232022460        1.0         2.0           3.0          0.500000
3  232438397      160.0         1.0         161.0        160.000000
4  230460314        2.0         8.0          10.0          0.250000
5  230459870        4.0         6.0          10.0          0.666667
6  230333930        0.0         2.0           2.0          0.000000
7  230595899        2.0         1.0           3.0          2.000000
8  232013274        0.0         2.0           2.0          0.000000
9  232029206       59.0         1.0          60.0         59.000000

In [31]:
unique_in_neighbors = edges.groupby("txId2")["txId1"].nunique()
unique_out_neighbors = edges.groupby("txId1")["txId2"].nunique()

unique_in_neighbors_full = (
    all_txids.map(unique_in_neighbors).fillna(0)
)

unique_out_neighbors_full = (
    all_txids.map(unique_out_neighbors).fillna(0)
)

print("Unique incoming neighbors:")
print(unique_in_neighbors_full.describe())

print("\nUnique outgoing neighbors:")
print(unique_out_neighbors_full.describe())

Unique incoming neighbors:
count    203769.000000
mean          1.150101
std           3.911132
min           0.000000
25%           0.000000
50%           1.000000
75%           1.000000
max         284.000000
Name: txId, dtype: float64

Unique outgoing neighbors:
count    203769.000000
mean          1.150101
std           1.894740
min           0.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         472.000000
Name: txId, dtype: float64

In [32]:
node_features["unique_in_neighbors"] = unique_in_neighbors_full
node_features["unique_out_neighbors"] = unique_out_neighbors_full

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "fan_in_out_ratio",
            "unique_in_neighbors",
            "unique_out_neighbors"
        ]
    ].head(10)
)

(203769, 173)

,txId,in_degree,out_degree,total_degree,fan_in_out_ratio,unique_in_neighbors,unique_out_neighbors
0,230425980,1.0,1.0,2.0,1.000000,1.0,1.0
1,5530458,1.0,1.0,2.0,1.000000,1.0,1.0
2,232022460,1.0,2.0,3.0,0.500000,1.0,2.0
3,232438397,160.0,1.0,161.0,160.000000,160.0,1.0
4,230460314,2.0,8.0,10.0,0.250000,2.0,8.0
5,230459870,4.0,6.0,10.0,0.666667,4.0,6.0
6,230333930,0.0,2.0,2.0,0.000000,0.0,2.0
7,230595899,2.0,1.0,3.0,2.000000,2.0,1.0
8,232013274,0.0,2.0,2.0,0.000000,0.0,2.0
9,232029206,59.0,1.0,60.0,59.000000,59.0,1.0

In [33]:
node_features["neighbor_count"] = (
    node_features["unique_in_neighbors"] +
    node_features["unique_out_neighbors"]
)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "unique_in_neighbors",
            "unique_out_neighbors",
            "neighbor_count"
        ]
    ].head(10)
)

(203769, 174)

        txId  unique_in_neighbors  unique_out_neighbors  neighbor_count
0  230425980                  1.0                   1.0             2.0
1    5530458                  1.0                   1.0             2.0
2  232022460                  1.0                   2.0             3.0
3  232438397                160.0                   1.0           161.0
4  230460314                  2.0                   8.0            10.0
5  230459870                  4.0                   6.0            10.0
6  230333930                  0.0                   2.0             2.0
7  230595899                  2.0                   1.0             3.0
8  232013274                  0.0                   2.0             2.0
9  232029206                 59.0                   1.0            60.0

In [34]:
node_features["flow_balance"] = (
    (node_features["in_degree"] - node_features["out_degree"]) /
    node_features["total_degree"]
)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "fan_in_out_ratio",
            "flow_balance"
        ]
    ].head(10)
)

(203769, 175)

,txId,in_degree,out_degree,total_degree,fan_in_out_ratio,flow_balance
0,230425980,1.0,1.0,2.0,1.000000,0.000000
1,5530458,1.0,1.0,2.0,1.000000,0.000000
2,232022460,1.0,2.0,3.0,0.500000,-0.333333
3,232438397,160.0,1.0,161.0,160.000000,0.987578
4,230460314,2.0,8.0,10.0,0.250000,-0.600000
5,230459870,4.0,6.0,10.0,0.666667,-0.200000
6,230333930,0.0,2.0,2.0,0.000000,-1.000000
7,230595899,2.0,1.0,3.0,2.000000,0.333333
8,232013274,0.0,2.0,2.0,0.000000,-1.000000
9,232029206,59.0,1.0,60.0,59.000000,0.966667

In [35]:
time_transaction_count = (
    node_features.groupby("Time_step")["txId"]
    .transform("count")
)

node_features["timestep_transaction_count"] = time_transaction_count

print(node_features.shape)

display(
    node_features[
        ["txId", "Time_step", "timestep_transaction_count"]
    ].head(10)
)

(203769, 176)

        txId  Time_step  timestep_transaction_count
0  230425980          1                        7880
1    5530458          1                        7880
2  232022460          1                        7880
3  232438397          1                        7880
4  230460314          1                        7880
5  230459870          1                        7880
6  230333930          1                        7880
7  230595899          1                        7880
8  232013274          1                        7880
9  232029206          1                        7880

In [36]:
min_time = node_features["Time_step"].min()
max_time = node_features["Time_step"].max()

node_features["time_position"] = (
    (node_features["Time_step"] - min_time) /
    (max_time - min_time)
)

print(node_features.shape)

display(
    node_features[
        ["txId", "Time_step", "time_position"]
    ].head(10)
)

(203769, 177)

        txId  Time_step  time_position
0  230425980          1            0.0
1    5530458          1            0.0
2  232022460          1            0.0
3  232438397          1            0.0
4  230460314          1            0.0
5  230459870          1            0.0
6  230333930          1            0.0
7  230595899          1            0.0
8  232013274          1            0.0
9  232029206          1            0.0

In [37]:
node_features["in_degree_ratio"] = (
    node_features["in_degree"] /
    node_features["total_degree"]
)

node_features["out_degree_ratio"] = (
    node_features["out_degree"] /
    node_features["total_degree"]
)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "in_degree_ratio",
            "out_degree_ratio"
        ]
    ].head(10)
)

(203769, 179)

,txId,in_degree,out_degree,total_degree,in_degree_ratio,out_degree_ratio
0,230425980,1.0,1.0,2.0,0.500000,0.500000
1,5530458,1.0,1.0,2.0,0.500000,0.500000
2,232022460,1.0,2.0,3.0,0.333333,0.666667
3,232438397,160.0,1.0,161.0,0.993789,0.006211
4,230460314,2.0,8.0,10.0,0.200000,0.800000
5,230459870,4.0,6.0,10.0,0.400000,0.600000
6,230333930,0.0,2.0,2.0,0.000000,1.000000
7,230595899,2.0,1.0,3.0,0.666667,0.333333
8,232013274,0.0,2.0,2.0,0.000000,1.000000
9,232029206,59.0,1.0,60.0,0.983333,0.016667

In [38]:
import numpy as np

node_features["log_in_degree"] = np.log1p(node_features["in_degree"])
node_features["log_out_degree"] = np.log1p(node_features["out_degree"])
node_features["log_total_degree"] = np.log1p(node_features["total_degree"])
node_features["log_neighbor_count"] = np.log1p(node_features["neighbor_count"])

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "neighbor_count",
            "log_in_degree",
            "log_out_degree",
            "log_total_degree",
            "log_neighbor_count"
        ]
    ].head(10)
)

(203769, 183)

,txId,in_degree,out_degree,total_degree,neighbor_count,log_in_degree,log_out_degree,log_total_degree,log_neighbor_count
0,230425980,1.0,1.0,2.0,2.0,0.693147,0.693147,1.098612,1.098612
1,5530458,1.0,1.0,2.0,2.0,0.693147,0.693147,1.098612,1.098612
2,232022460,1.0,2.0,3.0,3.0,0.693147,1.098612,1.386294,1.386294
3,232438397,160.0,1.0,161.0,161.0,5.081404,0.693147,5.087596,5.087596
4,230460314,2.0,8.0,10.0,10.0,1.098612,2.197225,2.397895,2.397895
5,230459870,4.0,6.0,10.0,10.0,1.609438,1.945910,2.397895,2.397895
6,230333930,0.0,2.0,2.0,2.0,0.000000,1.098612,1.098612,1.098612
7,230595899,2.0,1.0,3.0,3.0,1.098612,0.693147,1.386294,1.386294
8,232013274,0.0,2.0,2.0,2.0,0.000000,1.098612,1.098612,1.098612
9,232029206,59.0,1.0,60.0,60.0,4.094345,0.693147,4.110874,4.110874

In [39]:
time_degree_mean = (
    node_features.groupby("Time_step")["total_degree"]
    .transform("mean")
)

node_features["degree_vs_time_mean"] = (
    node_features["total_degree"] /
    time_degree_mean.replace(0, np.nan)
).fillna(0)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "Time_step",
            "total_degree",
            "timestep_transaction_count",
            "degree_vs_time_mean"
        ]
    ].head(10)
)

(203769, 184)

,txId,Time_step,total_degree,timestep_transaction_count,degree_vs_time_mean
0,230425980,1,2.0,7880,0.859887
1,5530458,1,2.0,7880,0.859887
2,232022460,1,3.0,7880,1.289830
3,232438397,1,161.0,7880,69.220864
4,230460314,1,10.0,7880,4.299433
5,230459870,1,10.0,7880,4.299433
6,230333930,1,2.0,7880,0.859887
7,230595899,1,3.0,7880,1.289830
8,232013274,1,2.0,7880,0.859887
9,232029206,1,60.0,7880,25.796595

In [40]:
node_features["high_in_degree"] = (
    node_features["in_degree"] >= 10
).astype(int)

node_features["high_out_degree"] = (
    node_features["out_degree"] >= 10
).astype(int)

node_features["high_total_degree"] = (
    node_features["total_degree"] >= 10
).astype(int)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "high_in_degree",
            "high_out_degree",
            "high_total_degree"
        ]
    ].head(10)
)

(203769, 187)

,txId,in_degree,out_degree,total_degree,high_in_degree,high_out_degree,high_total_degree
0,230425980,1.0,1.0,2.0,0,0,0
1,5530458,1.0,1.0,2.0,0,0,0
2,232022460,1.0,2.0,3.0,0,0,0
3,232438397,160.0,1.0,161.0,1,0,1
4,230460314,2.0,8.0,10.0,0,0,1
5,230459870,4.0,6.0,10.0,0,0,1
6,230333930,0.0,2.0,2.0,0,0,0
7,230595899,2.0,1.0,3.0,0,0,0
8,232013274,0.0,2.0,2.0,0,0,0
9,232029206,59.0,1.0,60.0,1,0,1

In [41]:
node_features["flow_imbalance"] = (
    (node_features["in_degree"] - node_features["out_degree"]).abs()
    / node_features["total_degree"]
)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "in_degree",
            "out_degree",
            "total_degree",
            "flow_balance",
            "flow_imbalance"
        ]
    ].head(10)
)

(203769, 188)

,txId,in_degree,out_degree,total_degree,flow_balance,flow_imbalance
0,230425980,1.0,1.0,2.0,0.000000,0.000000
1,5530458,1.0,1.0,2.0,0.000000,0.000000
2,232022460,1.0,2.0,3.0,-0.333333,0.333333
3,232438397,160.0,1.0,161.0,0.987578,0.987578
4,230460314,2.0,8.0,10.0,-0.600000,0.600000
5,230459870,4.0,6.0,10.0,-0.200000,0.200000
6,230333930,0.0,2.0,2.0,-1.000000,1.000000
7,230595899,2.0,1.0,3.0,0.333333,0.333333
8,232013274,0.0,2.0,2.0,-1.000000,1.000000
9,232029206,59.0,1.0,60.0,0.966667,0.966667

In [42]:
original_feature_cols = [
    col for col in features.columns
    if col.startswith("feature_")
]

node_features["feature_mean"] = features[original_feature_cols].mean(axis=1)
node_features["feature_std"] = features[original_feature_cols].std(axis=1)
node_features["feature_min"] = features[original_feature_cols].min(axis=1)
node_features["feature_max"] = features[original_feature_cols].max(axis=1)
node_features["feature_median"] = features[original_feature_cols].median(axis=1)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "feature_mean",
            "feature_std",
            "feature_min",
            "feature_max",
            "feature_median"
        ]
    ].head(10)
)

(203769, 193)

,txId,feature_mean,feature_std,feature_min,feature_max,feature_median
0,230425980,-0.152958,0.585355,-1.494057,1.488113,-0.139733
1,5530458,-0.218716,0.482527,-1.494024,1.366287,-0.140763
2,232022460,-0.306988,0.636442,-2.429065,2.448785,-0.152464
3,232438397,0.372426,1.984728,-2.772015,12.414558,-0.066858
4,230460314,-0.021889,0.729460,-1.943850,1.817237,-0.091258
5,230459870,-0.078320,0.571749,-1.592267,1.677228,-0.116742
6,230333930,-0.006581,0.674526,-1.943850,2.700700,-0.097524
7,230595899,-0.127918,1.039591,-2.841929,3.275536,-0.138876
8,232013274,-0.270332,0.550771,-1.499972,1.521399,-0.134546
9,232029206,0.205746,1.237420,-1.618971,6.220011,-0.079747

In [43]:
node_features["extreme_feature_count_2"] = (
    features[original_feature_cols].abs() > 2
).sum(axis=1)

node_features["extreme_feature_count_3"] = (
    features[original_feature_cols].abs() > 3
).sum(axis=1)

node_features["extreme_feature_count_5"] = (
    features[original_feature_cols].abs() > 5
).sum(axis=1)

print(node_features.shape)

display(
    node_features[
        [
            "txId",
            "extreme_feature_count_2",
            "extreme_feature_count_3",
            "extreme_feature_count_5"
        ]
    ].head(10)
)

(203769, 196)

,txId,extreme_feature_count_2,extreme_feature_count_3,extreme_feature_count_5
0,230425980,0,0,0
1,5530458,0,0,0
2,232022460,3,0,0
3,232438397,17,11,4
4,230460314,0,0,0
5,230459870,0,0,0
6,230333930,3,0,0
7,230595899,16,2,0
8,232013274,0,0,0
9,232029206,12,9,1

In [44]:
node_features.to_csv("node_features_engineered.csv", index=False)

In [45]:
print(node_features.shape)
print(node_features.columns.tolist())

(203769, 196)
['txId', 'Time_step', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_86', 'feature_87', 'feature_88', 'feature_89', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'feature_100', 'feature_101', 'feature_102', 'feature_103', 'feature_104', 'feature_105', 'feature_106', 'feature_107', 'feature_108', 'feature_109', 'feature_110', 'feature_111', 'feature_112', 'feature_113', 'feature_114', 'feature_115', 'feature_116', 'feature_117', 'feature_118', 'feature_119', 'feature_120', 'feature_121', 'feature_122', 'feature_123', 'feature_124', 'feature_125', 'feature_126', 'feature_127', 'feature_128', 'feature_129', 'feature_130', 'feature_131', 'feature_132', 'feature_133', 'feature_134', 'feature_135', 'feature_136', 'feature_137', 'feature_138', 'feature_139', 'feature_140', 'feature_141', 'feature_142', 'feature_143', 'feature_144', 'feature_145', 'feature_146', 'feature_147', 'feature_148', 'feature_149', 'feature_150', 'feature_151', 'feature_152', 'feature_153', 'feature_154', 'feature_155', 'feature_156', 'feature_157', 'feature_158', 'feature_159', 'feature_160', 'feature_161', 'feature_162', 'feature_163', 'feature_164', 'feature_165', 'in_degree', 'out_degree', 'total_degree', 'fan_in_out_ratio', 'unique_in_neighbors', 'unique_out_neighbors', 'neighbor_count', 'flow_balance', 'timestep_transaction_count', 'time_position', 'in_degree_ratio', 'out_degree_ratio', 'log_in_degree', 'log_out_degree', 'log_total_degree', 'log_neighbor_count', 'degree_vs_time_mean', 'high_in_degree', 'high_out_degree', 'high_total_degree', 'flow_imbalance', 'feature_mean', 'feature_std', 'feature_min', 'feature_max', 'feature_median', 'extreme_feature_count_2', 'extreme_feature_count_3', 'extreme_feature_count_5']

In [46]:
import os

print(os.path.exists("node_features_engineered.csv"))
print(os.path.getsize("node_features_engineered.csv") / (1024 * 1024), "MB")

True
683.7007522583008 MB